#pv
#pvc
#statefulset - mysql
#headless
#config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/temp/testfiles"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim: 
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap: 
            name: mysql-initdb-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-cm
data:
  init.sql: |
       CREATE DATABASE IF NOT EXIST order_service;
       CREATE DATABASE IF NOT EXIST payment_service;
       CREATE DATABASE IF NOT EXIST product_service;
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    