apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-servicve-app
spec:
  selector:
    matchLabels:
      app: product-servicve-app
  template:
    metadata:
      labels:
        app: product-servicve-app
    spec:
      containers:
      - name: product-servicve-app
        image: abhigyanr8/productservice:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9091
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
                key: eureka_server_address
                name: eureka-cm
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
               key:  config_url
               name: config-cm
        - name: DB_HOST
          valueFrom:
              configMapKeyRef:
               key:  hostname
               name: mysql-cm
---
apiVersion: v1
kind: Service
metadata:
  name: product-servicve-svc
spec:
  selector:
    app: product-service-app
  ports:
  - port: 80
    targetPort: 9091

