server:
  port: 9093
spring:
  application:
    name: CONFIGSERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhigyanr8/congigserver.git
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


#server.port=9093
#spring.application.name=CONFIGSERVICE
#spring.cloud.config.server.git.uri=https://github.com/abhigyanr8/congigserver.git
#spring.cloud.config.git.clone-on-start=true;
#
#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.service-url.defaultZone=${EUREKA_SERVER_ADDRESS}=http://localhost:8761/
